### ISSUE TITLE
readlink: illegal option -- f

### ISSUE THREAD

**Issue by wdavidw** [kriszyp/cpm#11]
On OSX Lion: install is ok but issuing `cpm` output:

``` bash
readlink: illegal option -- f
usage: readlink [-n] [file ...]
Exception in thread "main" java.lang.NoClassDefFoundError: org/mozilla/javascript/tools/shell/Main
Caused by: java.lang.ClassNotFoundException: org.mozilla.javascript.tools.shell.Main
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by wdavidw** [comment]
Removing the `-f` argument on line 13 from seems to work on osx:

``` bash
CPM_PATH="$(dirname "$(readlink $0)")"
```

**Comment by davidLeonardi** [comment]
Same issue on OSX mountain lion .
Modifying said line fixed the issue for me as well.
